ci: Ensure `actions/dist` is up-to-date

diff --git a/.github/workflows/validate.yml b/.github/workflows/validate.yml
--- a/.github/workflows/validate.yml
+++ b/.github/workflows/validate.yml
@@ -16,6 +16,7 @@ jobs:
       - uses: ./.github/actions/setup
       - run: bun run build
       - run: bun check
+
   tests:
     name: Tests
     runs-on: ubuntu-24.04
@@ -23,3 +24,19 @@ jobs:
       - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
       - uses: ./.github/actions/setup
       - run: bun test
+
+  actions-build:
+    name: Actions Built
+    runs-on: ubuntu-24.04
+    steps:
+      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
+      - uses: ./.github/actions/setup
+      - run: bun run build
+      - name: Check for git changes
+        run: |
+          if [ -n "$(git status --porcelain)" ]; then
+            echo -e "Error: Detected changes in actions/dist. These files should be committed.\n\nRun \`bun run build\` to update the actions and commit the change."
+            git status
+            git diff
+            exit 1
+          fi
